### ISSUE TITLE
Unexpected OpenGL error 1282 on MacOS

### ISSUE THREAD

**Issue by benstox** [HexDecimal/libtcod-vcpkg-template#1]
Hello, I was able to build this fine, however running the project gives:
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  libtcod 1.20.1 <path to repo>/libtcod/src/libtcod/renderer_gl1.c:285
Unexpected OpenGL error 1282.
zsh: abort      ./build/bin/libtcod-vcpkg-template
```
on MacOS Big Sur 11.0.1. Do you know what I need to do to get this running? Thanks.

**Comment by HexDecimal** [comment]
1282 means invalid operation.  It could be that your MacOS drivers don't like one of the older OpenGL functions.

MacOS insists on deprecating OpenGL and often has issues with it.  It doesn't help that `TCOD_RENDERER_OPENGL` uses the oldest OpenGL functions in the standard.  I'd be curious if you get a similar error with `TCOD_RENDERER_OPENGL2`.

Use `TCOD_RENDERER_SDL2` to fix the issue.  SDL will likely use MacOS's Metal rendering and should have the least problems unless there's some kind of driver issue.

**Comment by HexDecimal** [comment]
I forgot this was the template project.

Looks like `TCOD_RENDERER_OPENGL2` failed to load and fell back to `TCOD_RENDERER_OPENGL` which then failed on running.  I'm just going to switch the default renderer to `TCOD_RENDERER_SDL2`.

**Comment by HexDecimal** [comment]
I changed the default to `TCOD_RENDERER_SDL2` and updated the libtcod and vcpkg submodules to fetch libtcod's improved SDL2 renderer.

I've also added build artifacts and deployment, so you can try the [MacOS build here](https://github.com/HexDecimal/libtcod-vcpkg-template/releases) if you like (tell me if they work if you do that.)

And I've added a font file to test data file packaging, since that was an obvious missing feature.

**Comment by benstox** [comment]
Thanks a lot. `TCOD_RENDERER_SDL2` has indeed solved it.
